/* ============================================================
   JLPT_TEST — Bank soal "Tes Kosakata & Tata Bahasa" bergaya
   ujian resmi (format JCT: 語彙 & bunpou pilihan ganda 4 opsi),
   BERBEDA dari mode "Pola Kalimat" yang sudah ada sebelumnya
   (yang berbasis contoh kalimat per pola). Mode ini murni soal
   ujian: cara baca kanji, penulisan kanji, isian kosakata,
   sinonim/makna serupa, dan penggunaan kata yang tepat.
   Sumber: JCT5 (初級≈N5), JCT4 (準中級≈N4), JCT3 (中級≈N3).
   ============================================================ */
const JLPT_TEST = [
/* ============ N5 (JCT5 初級) — 35 soal ============ */
{level:"N5", section:"Cara Baca Kanji", qText:"あちらに <b>電車</b>が とまって いる。", options:["くるま","ふね","でんしゃ","ひこうき"], correctAns:"でんしゃ"},
{level:"N5", section:"Cara Baca Kanji", qText:"<b>年</b>に 一かい 大そうじを する。", options:["ねん","しゅう","たま","つき"], correctAns:"ねん"},
{level:"N5", section:"Cara Baca Kanji", qText:"<b>大人</b>に なったら たくさん りょこうが したい。", options:["だいじん","おおじん","おんな","おとな"], correctAns:"おとな"},
{level:"N5", section:"Cara Baca Kanji", qText:"ここから <b>東</b>に 行くと うみに つく。", options:["ひがし","にし","みなみ","きた"], correctAns:"ひがし"},
{level:"N5", section:"Cara Baca Kanji", qText:"ゲームを かうために お<b>金</b>を ためる。", options:["かね","きん","こん","かな"], correctAns:"かね"},
{level:"N5", section:"Cara Baca Kanji", qText:"わたしの 母は <b>白い</b> ふくが すきだ。", options:["あか","きいろ","あお","しろ"], correctAns:"しろ"},
{level:"N5", section:"Cara Baca Kanji", qText:"これは <b>百年前</b>の おさらだ。", options:["せんねんまえ","ひゃくねんまえ","じゅうねんまえ","いちねんまえ"], correctAns:"ひゃくねんまえ"},
{level:"N5", section:"Cara Baca Kanji", qText:"りんごを <b>一つ</b> ください。", options:["ひとつ","ふたつ","いつつ","ななつ"], correctAns:"ひとつ"},
{level:"N5", section:"Cara Baca Kanji", qText:"いもうとの <b>話</b>は いつも おもしろい。", options:["かれし","いし","はなし","れきし"], correctAns:"はなし"},
{level:"N5", section:"Cara Baca Kanji", qText:"かんじを <b>書く</b>のは むずかしい。", options:["ひく","かく","まく","あく"], correctAns:"かく"},
{level:"N5", section:"Cara Baca Kanji", qText:"今日は <b>天気</b>が いい。", options:["うんき","てんき","きこう","きぶん"], correctAns:"てんき"},
{level:"N5", section:"Cara Baca Kanji", qText:"だれかが <b>来</b>たら おしえて ください。", options:["いたら","したら","みたら","きたら"], correctAns:"きたら"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>なか</b>に 入って まって いて ください。", options:["中","外","間","何"], correctAns:"中"},
{level:"N5", section:"Penulisan Kanji", qText:"カナダは ゆきの おおい <b>くに</b>だ。", options:["日","四","国","円"], correctAns:"国"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>もくようび</b>は 学校が はやく おわる。", options:["土","月","火","木"], correctAns:"木"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>ごご</b>から さんぽに でかけよう。", options:["午前","午後","半前","半後"], correctAns:"午後"},
{level:"N5", section:"Penulisan Kanji", qText:"今日は <b>あめ</b>が ふった。", options:["南","右","水","雨"], correctAns:"雨"},
{level:"N5", section:"Penulisan Kanji", qText:"あたまが いたいから しごとを <b>やすんだ</b>。", options:["休んだ","小んだ","木んだ","本んだ"], correctAns:"休んだ"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>ちょこれーと</b>が だいすきだ。", options:["キョコレート","キョコルート","チョコレート","チョコルート"], correctAns:"チョコレート"},
{level:"N5", section:"Penulisan Kanji", qText:"今日は <b>やま</b>に あそびに 行く。", options:["川","山","三","出"], correctAns:"山"},
{level:"N5", section:"Isian Kosakata", qText:"友だちに（　）を 書きます。", options:["えんぴつ","はなし","がっこう","てがみ"], correctAns:"てがみ"},
{level:"N5", section:"Isian Kosakata", qText:"えいがかんは どこに あるか（　）ますか。", options:["はじまり","わかり","まいり","はいり"], correctAns:"わかり"},
{level:"N5", section:"Isian Kosakata", qText:"（　）すこしで しごとが おわります。", options:["あと","あまり","また","とても"], correctAns:"あと"},
{level:"N5", section:"Isian Kosakata", qText:"ごはんの 前に てを（　）ましょう。", options:["つかい","うたい","ねがい","あらい"], correctAns:"あらい"},
{level:"N5", section:"Isian Kosakata", qText:"やさいを（　）ください。", options:["のって","あって","きって","はしって"], correctAns:"きって"},
{level:"N5", section:"Isian Kosakata", qText:"（　）かばんを かった。", options:["おいしい","あたらしい","いそがしい","すずしい"], correctAns:"あたらしい"},
{level:"N5", section:"Isian Kosakata", qText:"そこは きれいな 川で（　）だ。", options:["ゆうめい","じょうぶ","じょうず","にぎやか"], correctAns:"ゆうめい"},
{level:"N5", section:"Isian Kosakata", qText:"しつもんが ある人は てを（　）。", options:["ひいて","おして","つけて","あげて"], correctAns:"あげて"},
{level:"N5", section:"Isian Kosakata", qText:"あには（　）いそがしそうだ。", options:["いつも","あまり","きっと","だんだん"], correctAns:"いつも"},
{level:"N5", section:"Isian Kosakata", qText:"Ａ「今日は 何が（　）ですか」　Ｂ「パンが いいです」", options:["のみたい","たべたい","すわりたい","ならびたい"], correctAns:"たべたい"},
{level:"N5", section:"Makna Serupa", qText:"もっと 大きい ズボンは ありますか。", options:["あかい ズボンが いいです。","これは 小さいです。","これは かわいくないです。","これは 高いです。"], correctAns:"これは 小さいです。"},
{level:"N5", section:"Makna Serupa", qText:"父は ぎんこうに つとめて いる。", options:["ぎんこうで はたらいている かぞくが いる。","ここは 友だちが はたらく ぎんこうだ。","かぞくと いっしょに ぎんこうに 行く。","この ぎんこうで はたらきたい。"], correctAns:"ぎんこうで はたらいている かぞくが いる。"},
{level:"N5", section:"Makna Serupa", qText:"この 時間は いつも ちょっとだけ おかしを 食べる。", options:["毎日 おかしを たくさん 食べる。","毎日 すこし おかしを 食べる。","ときどき おかしを 食べる。","おかしは からだに わるいから 食べない。"], correctAns:"毎日 すこし おかしを 食べる。"},
{level:"N5", section:"Makna Serupa", qText:"この おみせは 20時までです。", options:["20時前は かいものが できません。","この おみせは 20時に ひらきます。","かいものを するなら 20時に なってからが いいです。","20時になったら この おみせは しまります。"], correctAns:"20時になったら この おみせは しまります。"},
{level:"N5", section:"Makna Serupa", qText:"らいしゅうは もっと さむくなる。", options:["だんだん あたたかくなる。","らいしゅうは ゆきは ふらない。","こんしゅうも さむいが らいしゅうも さむい。","らいしゅうは コートは いらない。"], correctAns:"こんしゅうも さむいが らいしゅうも さむい。"},

/* ============ N4 (JCT4 準中級) — 35 soal ============ */
{level:"N4", section:"Cara Baca Kanji", qText:"私は <b>切手</b>を 集める ことが すきだ。", options:["せっしゅ","きって","きりかた","せつじつ"], correctAns:"きって"},
{level:"N4", section:"Cara Baca Kanji", qText:"私は 毎日 外で <b>運動</b>を している。", options:["どうこう","こうどう","うんどう","うんこう"], correctAns:"うんどう"},
{level:"N4", section:"Cara Baca Kanji", qText:"あなたからは いつも <b>元気</b>を もらっている。", options:["げんき","どうき","じょうき","かんき"], correctAns:"げんき"},
{level:"N4", section:"Cara Baca Kanji", qText:"去年に くらべて 今年は <b>旅行</b>している 人が 多い。", options:["そうこう","しゅぎょう","しぎょう","りょこう"], correctAns:"りょこう"},
{level:"N4", section:"Cara Baca Kanji", qText:"私は 毎日 英語を <b>勉強</b>している。", options:["ざんぎょう","こうちょう","がんじょう","べんきょう"], correctAns:"べんきょう"},
{level:"N4", section:"Cara Baca Kanji", qText:"<b>会社</b>に 行く 用意を する。", options:["ぎょうかい","かいしゃ","こうじょう","けんしょう"], correctAns:"かいしゃ"},
{level:"N4", section:"Cara Baca Kanji", qText:"学校の 授業で <b>作文</b>を 書いた。", options:["しょうもん","ぶんしょう","さくぶん","かくのう"], correctAns:"さくぶん"},
{level:"N4", section:"Cara Baca Kanji", qText:"わたしは 英語を <b>習って</b>います。", options:["はかって","わかって","ならって","しって"], correctAns:"ならって"},
{level:"N4", section:"Cara Baca Kanji", qText:"言葉の <b>意味</b>を 考える。", options:["あじみ","いみ","いけん","みかく"], correctAns:"いみ"},
{level:"N4", section:"Penulisan Kanji", qText:"私は <b>かしゅ</b>に なりたいです。", options:["学習","工業","家主","歌手"], correctAns:"歌手"},
{level:"N4", section:"Penulisan Kanji", qText:"いつまでも <b>がくせい</b>で いたい。", options:["楽生","題生","学生","勉生"], correctAns:"学生"},
{level:"N4", section:"Penulisan Kanji", qText:"母は <b>あかるい</b> 人だ。", options:["赤るい","明るい","安るい","秋るい"], correctAns:"明るい"},
{level:"N4", section:"Penulisan Kanji", qText:"いつか <b>せかい</b>を 旅行したい。", options:["青海","海外","世界","世間"], correctAns:"世界"},
{level:"N4", section:"Penulisan Kanji", qText:"あなたは 私に 本を <b>かして</b>くれた。", options:["貸して","買して","書して","家して"], correctAns:"貸して"},
{level:"N4", section:"Penulisan Kanji", qText:"大きな <b>たてもの</b>の 中に 入る。", options:["立物","建物","立場","質問"], correctAns:"建物"},
{level:"N4", section:"Isian Kosakata", qText:"私は 今から ごはんを（　）。", options:["話す","食べる","聞く","すわる"], correctAns:"食べる"},
{level:"N4", section:"Isian Kosakata", qText:"今日は（　）と 買い物に 行く。", options:["洋服","本","食べ物","友だち"], correctAns:"友だち"},
{level:"N4", section:"Isian Kosakata", qText:"駅で（　）を 待つ。", options:["学校","ゆめ","歌","電車"], correctAns:"電車"},
{level:"N4", section:"Isian Kosakata", qText:"きのうは 風が（　）。", options:["強かった","ふとかった","重かった","安かった"], correctAns:"強かった"},
{level:"N4", section:"Isian Kosakata", qText:"私は 休みの日には（　）を 読む。", options:["空","毎日","映画","本"], correctAns:"本"},
{level:"N4", section:"Isian Kosakata", qText:"母は 絵を かくのが（　）。", options:["とおい","近い","うまい","高い"], correctAns:"うまい"},
{level:"N4", section:"Isian Kosakata", qText:"今日は 天気が（　）から、出かけたい。", options:["多い","よい","おそい","ほそい"], correctAns:"よい"},
{level:"N4", section:"Isian Kosakata", qText:"今から 家に（　）。", options:["歌う","書く","帰る","食べる"], correctAns:"帰る"},
{level:"N4", section:"Isian Kosakata", qText:"あなたは やさしいから 友だちが（　）いる。", options:["たくさん","少し","大きく","小さく"], correctAns:"たくさん"},
{level:"N4", section:"Isian Kosakata", qText:"冬は さむいが、夏は（　）。", options:["長い","おそい","あつい","こわい"], correctAns:"あつい"},
{level:"N4", section:"Makna Serupa", qText:"今日は たくさん 勉強したので もう ねる。", options:["勉強を しないと いけない。","勉強は とても すきだ。","勉強は これからも する。","今日は もう 勉強しない。"], correctAns:"今日は もう 勉強しない。"},
{level:"N4", section:"Makna Serupa", qText:"あの 人の 洋服が かわいい。", options:["あの 人の 洋服が すきでは ない。","あの 人の 洋服が すきだ。","あの 人の 洋服を わたしも 持っている。","あの 人の 洋服は よく ない。"], correctAns:"あの 人の 洋服が すきだ。"},
{level:"N4", section:"Makna Serupa", qText:"図書館で さわいでは いけません。", options:["図書館で うるさくしては いけません。","図書館で さわっては いけません。","図書館で さんぽしては いけません。","図書館で 走っては いけません。"], correctAns:"図書館で うるさくしては いけません。"},
{level:"N4", section:"Makna Serupa", qText:"父は いそいで 家を 出た。", options:["父は 歩いて 家を 出た。","父は いつもと 同じように 家を 出た。","父は すぐに 家を 出た。","父は 何度も 家を 出た。"], correctAns:"父は すぐに 家を 出た。"},
{level:"N4", section:"Makna Serupa", qText:"私は 友だちと いっしょに 学校に 行く。", options:["私は 学校まで 友だちと 歩く。","私は 学校が すきでは ない。","私は 学校に 行っていない。","私は 友だちと 学校が すきだ。"], correctAns:"私は 学校まで 友だちと 歩く。"},
{level:"N4", section:"Penggunaan Kata", qText:"家族", options:["私には ３人の 家族が いる。","家族を 使った おいしい 料理を 作る。","日曜日は いつも 家族に 行っている。","つぎの 休みは 家族を しよう。"], correctAns:"私には ３人の 家族が いる。"},
{level:"N4", section:"Penggunaan Kata", qText:"うれしい", options:["今日の 天気は いつもより うれしいみたいだ。","君の 家の 犬は とても うれしい 犬だね。","友だちに プレゼントを もらって うれしい。","見たことない うれしい 鳥が とんで きた。"], correctAns:"友だちに プレゼントを もらって うれしい。"},
{level:"N4", section:"Penggunaan Kata", qText:"ときどき", options:["今の 時間は ３時 ときどきだ。","私は ときどき ひとりで 歌っている。","見ているだけで 気持ちが ときどき してくる。","あなたは ときどきのように おくれて きますね。"], correctAns:"私は ときどき ひとりで 歌っている。"},
{level:"N4", section:"Penggunaan Kata", qText:"借りる", options:["明日から 新しい 仕事を 借ります。","食べ物を 借りながら 話しては いけません。","あの人は 多くの人に 借りられて います。","あなたの ノートを 借りても よいですか。"], correctAns:"あなたの ノートを 借りても よいですか。"},
{level:"N4", section:"Penggunaan Kata", qText:"ねむい", options:["どうしても ねむいので 少しだけ ねます。","チョコレートは ねむいから 大すきだ。","父が 作る カレーは いつも ねむい。","明日は もっと ねむいことが 起きると 思う。"], correctAns:"どうしても ねむいので 少しだけ ねます。"},

/* ============ N3 (JCT3 中級) — 35 soal ============ */
{level:"N3", section:"Cara Baca Kanji", qText:"試験に向けて教科書の内容を<b>暗記</b>する。", options:["きさい","あんしょう","あんき","きおく"], correctAns:"あんき"},
{level:"N3", section:"Cara Baca Kanji", qText:"今までで一番の<b>困難</b>を迎えている。", options:["こんきゅう","いんすう","いんが","こんなん"], correctAns:"こんなん"},
{level:"N3", section:"Cara Baca Kanji", qText:"少しだけ考える時間が<b>必要</b>だ。", options:["かんよう","ひつよう","ひっす","かんしょう"], correctAns:"ひつよう"},
{level:"N3", section:"Cara Baca Kanji", qText:"人は生まれながらに仕事を自ら選び働く<b>権利</b>をもっている。", options:["しょうき","けんり","そうり","こうき"], correctAns:"けんり"},
{level:"N3", section:"Cara Baca Kanji", qText:"弟は家族の中で一番<b>身長</b>が高い。", options:["せいちょう","しんたい","せたけ","しんちょう"], correctAns:"しんちょう"},
{level:"N3", section:"Cara Baca Kanji", qText:"ケーキを人数に合わせて<b>平等</b>に切り分ける。", options:["びょうどう","へいじょう","こうへい","ひょうてい"], correctAns:"びょうどう"},
{level:"N3", section:"Cara Baca Kanji", qText:"友達から結婚の<b>報告</b>を受ける。", options:["しょうそく","つうしん","ほうこく","こうこく"], correctAns:"ほうこく"},
{level:"N3", section:"Cara Baca Kanji", qText:"<b>祖母</b>は今年で85歳になる。", options:["そぼ","そふ","おじ","おば"], correctAns:"そぼ"},
{level:"N3", section:"Penulisan Kanji", qText:"朝早くから<b>れつ</b>にならんでいます。", options:["例","冷","礼","列"], correctAns:"列"},
{level:"N3", section:"Penulisan Kanji", qText:"この地域も<b>むかし</b>は大勢の人が住んでいた。", options:["現","際","末","昔"], correctAns:"昔"},
{level:"N3", section:"Penulisan Kanji", qText:"勉強に<b>かんけい</b>のないものを学校に持ってこないでください。", options:["関係","間係","関形","間形"], correctAns:"関係"},
{level:"N3", section:"Penulisan Kanji", qText:"ただいまお茶を持って<b>まいります</b>。", options:["満り","参り","回り","末り"], correctAns:"参り"},
{level:"N3", section:"Penulisan Kanji", qText:"かぜのため欠席することを先生に<b>つたえる</b>。", options:["伝える","頼える","続える","違える"], correctAns:"伝える"},
{level:"N3", section:"Penulisan Kanji", qText:"何を<b>こうふく</b>と感じるかは人それぞれだ。", options:["向福","光福","幸福","考福"], correctAns:"幸福"},
{level:"N3", section:"Penulisan Kanji", qText:"新しいドラマの<b>こうせい</b>を考える。", options:["向性","更生","構成","候声"], correctAns:"構成"},
{level:"N3", section:"Penulisan Kanji", qText:"<b>あいする</b>子供のために一生懸命に働く。", options:["想する","愛する","情する","好する"], correctAns:"愛する"},
{level:"N3", section:"Isian Kosakata", qText:"私たちは大学の近くの喫茶店で初めて（　）。", options:["取り上げた","受け取った","出会った","気に入った"], correctAns:"出会った"},
{level:"N3", section:"Isian Kosakata", qText:"睡眠時間が（　）していると疲れがたまりやすくなる。", options:["不足","心配","吸収","左右"], correctAns:"不足"},
{level:"N3", section:"Isian Kosakata", qText:"彼はこの町の（　）場所を知っている。", options:["あらゆる","単なる","いわゆる","どんな"], correctAns:"あらゆる"},
{level:"N3", section:"Isian Kosakata", qText:"転んですぐに、足に（　）痛みを感じた。", options:["明るい","よろしい","上手い","はげしい"], correctAns:"はげしい"},
{level:"N3", section:"Isian Kosakata", qText:"（　）行きたくても、宿題を終えるまでは行ってはいけません。", options:["あまり","どんなに","たしかに","どこも"], correctAns:"どんなに"},
{level:"N3", section:"Isian Kosakata", qText:"この商品はとても人気で（　）手に入らない。", options:["なるべく","なかなか","もしも","なるほど"], correctAns:"なかなか"},
{level:"N3", section:"Isian Kosakata", qText:"あなたの（　）のケーキも冷蔵庫に入っています。", options:["中","わけ","分","もの"], correctAns:"分"},
{level:"N3", section:"Isian Kosakata", qText:"電話の（　）のおかげで、今の便利な生活がある。", options:["発明","許可","学習","記入"], correctAns:"発明"},
{level:"N3", section:"Isian Kosakata", qText:"彼女はいつも（　）研究をしている。", options:["有利に","新鮮に","熱心に","丈夫に"], correctAns:"熱心に"},
{level:"N3", section:"Makna Serupa", qText:"社長が問題を起こしたため、会社の商品の<b>イメージ</b>が悪くなった。", options:["印象","制度","質","評判"], correctAns:"印象"},
{level:"N3", section:"Makna Serupa", qText:"日本に来て１年が経ち、<b>多少</b>日本語を話すことができるようになった。", options:["かなり","容易に","少し","意外に"], correctAns:"少し"},
{level:"N3", section:"Makna Serupa", qText:"仲の悪い二人の意見が、めずらしく<b>一致した</b>。", options:["変わった","協力した","同じだった","けんかした"], correctAns:"同じだった"},
{level:"N3", section:"Makna Serupa", qText:"その日は彼女にとって、<b>一生</b>忘れられない日となった。", options:["しばらくの間","一年間","今までで一番","生きている間"], correctAns:"生きている間"},
{level:"N3", section:"Makna Serupa", qText:"雨は夕方にかけて<b>いっそう</b>強くなるそうだ。", options:["急に","もっと","やはり","いつも通り"], correctAns:"もっと"},
{level:"N3", section:"Penggunaan Kata", qText:"ふと", options:["外がとてもあついので、家の中に入ってふとした。","ふとすると、私も彼と同じ大学に行くかもしれない。","散歩をしていたときに、ふと彼のことを思い出した。","弟の誕生日プレゼントに、ふと漫画を買ってあげた。"], correctAns:"散歩をしていたときに、ふと彼のことを思い出した。"},
{level:"N3", section:"Penggunaan Kata", qText:"じゃま", options:["今は勉強しているので、じゃまをしないでください。","その日はじゃまになるまで、外で友達と遊んでいた。","何かじゃまがあれば、いつでも私にお電話ください。","今日はあついので、じゃまには気をつけてください。"], correctAns:"今は勉強しているので、じゃまをしないでください。"},
{level:"N3", section:"Penggunaan Kata", qText:"悪口", options:["彼女は性格が悪口であるため、友達が少ない。","先生が悪口してくれたおかげで成績が上がった。","私は悪口なので、食べ物の味がよくわからない。","本人がいないところで悪口を言うのはよくない。"], correctAns:"本人がいないところで悪口を言うのはよくない。"},
{level:"N3", section:"Penggunaan Kata", qText:"訓練", options:["火事に備えて訓練をしましょう。","彼は訓練な人なので、人から信頼されている。","この問題は訓練で私には解くことができません。","どんなことも訓練に行えば、上手になります。"], correctAns:"火事に備えて訓練をしましょう。"},
{level:"N3", section:"Penggunaan Kata", qText:"気に入る", options:["あの箱の中には何が入っているのか気に入る。","このかばんは、かるくてかわいいので気に入った。","図書館は静かなので、勉強の内容が気に入る。","今日は朝早くから外出したので、気に入った。"], correctAns:"このかばんは、かるくてかわいいので気に入った。"},
/* ============ N5 — Tata Bahasa (JCT5 D 文法) ============ */
{level:"N5", section:"Tata Bahasa", qText:"わたし（　）お父さんは あたまが いいです。", options:["に","の","が","は"], correctAns:"の"},
{level:"N5", section:"Tata Bahasa", qText:"あさ8時におきて 学校（　）行きます。", options:["に","を","が","と"], correctAns:"に"},
{level:"N5", section:"Tata Bahasa", qText:"ボールペン（　）てがみを書いた。", options:["を","で","に","も"], correctAns:"で"},
{level:"N5", section:"Tata Bahasa", qText:"わたしは いもうと（　）いっしょに かいものに行った。", options:["で","の","が","と"], correctAns:"と"},
{level:"N5", section:"Tata Bahasa", qText:"このどうぶつは いぬでは（　）。", options:["しません","いません","ありません","なりません"], correctAns:"ありません"},
{level:"N5", section:"Tata Bahasa", qText:"えきは（　）から あるいて5分くらいです。", options:["いつ","どれ","その","ここ"], correctAns:"ここ"},
{level:"N5", section:"Tata Bahasa", qText:"（　）ふくが ほしいですか。", options:["どんな","だれに","どこに","なにを"], correctAns:"どんな"},
{level:"N5", section:"Tata Bahasa", qText:"としょかんでは（　）してください。", options:["しずかだ","しずかな","しずかに","しずか"], correctAns:"しずかに"},
{level:"N5", section:"Tata Bahasa", qText:"だんだん（　）なってきた。", options:["くらい","くらく","くらき","くらか"], correctAns:"くらく"},
{level:"N5", section:"Tata Bahasa", qText:"本を（　）前に、このかみに名前を書いてください。", options:["かりる","かりた","かりて","かりない"], correctAns:"かりる"},
{level:"N5", section:"Tata Bahasa", qText:"（　）おかしは すきじゃないです。", options:["あまみ","あまく","あまさ","あまい"], correctAns:"あまい"},
{level:"N5", section:"Tata Bahasa", qText:"さいふをかばんに（　）でかけましょう。", options:["いれよう","いれたら","いれると","いれろ"], correctAns:"いれたら"},
{level:"N5", section:"Tata Bahasa", qText:"（　）できたすいぞくかんに行こう。", options:["ちかくに","ちかくを","ちかくは","ちかくが"], correctAns:"ちかくに"},
{level:"N5", section:"Tata Bahasa", qText:"時間がすこししか（　）。", options:["あります","ありました","ありません","ある"], correctAns:"ありません"},
{level:"N5", section:"Tata Bahasa", qText:"このいえは（　）きれいだ。", options:["いつの","いつが","いつか","いつも"], correctAns:"いつも"},
{level:"N5", section:"Tata Bahasa", qText:"へやにだれ（　）いますか。", options:["は","か","も","に"], correctAns:"か"},
{level:"N5", section:"Susun Kalimat (★)", qText:"これを　＿＿　＿＿　★　＿＿　いいですか。<br><small style='color:var(--sub)'>Susun: たべおわったら／ほかの／りょうりを／たのんで — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["たべおわったら","ほかの","りょうりを","たのんで"], correctAns:"りょうりを"},
{level:"N5", section:"Susun Kalimat (★)", qText:"けさ　＿＿　＿＿　★　＿＿　わすれた。<br><small style='color:var(--sub)'>Susun: でんきを／へやの／わたしは／けし — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["でんきを","へやの","わたしは","けし"], correctAns:"でんきを"},
{level:"N5", section:"Susun Kalimat (★)", qText:"これは　＿＿　＿＿　★　＿＿　です。<br><small style='color:var(--sub)'>Susun: つかう／パスポート／しゃしん／に — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["つかう","パスポート","しゃしん","に"], correctAns:"つかう"},
{level:"N5", section:"Susun Kalimat (★)", qText:"あなたは　＿＿　＿＿　★　＿＿　のですか。<br><small style='color:var(--sub)'>Susun: なろうと／どうして／している／いしゃに — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["なろうと","どうして","している","いしゃに"], correctAns:"なろうと"},
{level:"N5", section:"Susun Kalimat (★)", qText:"この　＿＿　＿＿　★　＿＿　ました。<br><small style='color:var(--sub)'>Susun: わたしと／つくり／ともだちで／おかしは — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["わたしと","つくり","ともだちで","おかしは"], correctAns:"ともだちで"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【１】に入るものは？", options:["つくってください","つくりましょう","つくろう","つくります"], correctAns:"つくります"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【２】に入るものは？", options:["まだ","いつか","あと","もう"], correctAns:"まだ"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【３】に入るものは？", options:["いそがしく","いそがしい","いそがし","いそがしさ"], correctAns:"いそがしい"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Anna):</b><br>おとうとは とても あたまが いいです。毎日たくさんべんきょうをして【４】。わたしはべんきょうがすきではありません。【５】、今日からわたしもおとうとといっしょにべんきょうします。<br><br>【４】に入るものは？", options:["いただきます","いらっしゃい","います","いります"], correctAns:"います"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Anna):</b><br>おとうとは とても あたまが いいです。毎日たくさんべんきょうをして【４】。わたしはべんきょうがすきではありません。【５】、今日からわたしもおとうとといっしょにべんきょうします。<br><br>【５】に入るものは？", options:["先に","そして","しかし","では"], correctAns:"しかし"},

/* ============ N4 — Tata Bahasa (JCT4 D 文法) ============ */
{level:"N4", section:"Tata Bahasa", qText:"明日は出発が早いので（　）ようにしましょう。", options:["まちがえない","まちがえず","まちがえて","まちがえた"], correctAns:"まちがえない"},
{level:"N4", section:"Tata Bahasa", qText:"ここからのけしきもすっかりかわって（　）。", options:["しません","しまった","しまいません","しました"], correctAns:"しまった"},
{level:"N4", section:"Tata Bahasa", qText:"このはこには（　）が入っていると思いますか。", options:["どこ","だれ","なぜ","何"], correctAns:"何"},
{level:"N4", section:"Tata Bahasa", qText:"お金が（　）プレゼントを買えたのに。", options:["あれば","あって","あった","ある"], correctAns:"あれば"},
{level:"N4", section:"Tata Bahasa", qText:"私の父は（　）やさしい人だ。", options:["きびしいと","きびしくない","きびしいが","きびしくだが"], correctAns:"きびしいが"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「どうしてアメリカに行こうと思ったのですか」Ｂ「映画を（　）勉強をしたかったんです」", options:["作ら","作ろ","作れ","作る"], correctAns:"作る"},
{level:"N4", section:"Tata Bahasa", qText:"ここではたくさんの（　）魚を見ることができます。", options:["動物に","動物や","動物も","動物で"], correctAns:"動物や"},
{level:"N4", section:"Tata Bahasa", qText:"私は（　）足がはやくない。", options:["兄など","兄だって","兄ほど","兄まで"], correctAns:"兄ほど"},
{level:"N4", section:"Tata Bahasa", qText:"何を買おうとしていたのかぜんぜん（　）。", options:["思い出した","思い出せない","思い出そう","思い出す"], correctAns:"思い出せない"},
{level:"N4", section:"Tata Bahasa", qText:"あのときうそを（　）よかった。", options:["ついた","ついたから","つかなければ","つかない"], correctAns:"つかなければ"},
{level:"N4", section:"Tata Bahasa", qText:"私と姉を（　）ください。", options:["くらべないで","くらべられて","くらべよう","くらべると"], correctAns:"くらべないで"},
{level:"N4", section:"Tata Bahasa", qText:"このイヌに（　）。", options:["さわったり","さわり","さわれば","さわるな"], correctAns:"さわるな"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「かれはじゅぎょう中ねて（　）いるね」Ｂ「つぎのテストがしんぱいだね」", options:["しか","ばかり","いって","きて"], correctAns:"ばかり"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「休みの日は何をしているんですか」Ｂ「テレビを（　）ことが多いです」", options:["みた","みて","みたらしい","みている"], correctAns:"みている"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「コーヒーを（　）お話ししませんか」Ｂ「いいですね、そうしましょう」", options:["飲みながら","飲もうと","飲めず","飲め"], correctAns:"飲みながら"},
{level:"N4", section:"Susun Kalimat (★)", qText:"しょうらいの　＿＿　＿＿　★　＿＿　ことです。<br><small style='color:var(--sub)'>Susun: 行く／大学に／ゆめは／アメリカの — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["行く","大学に","ゆめは","アメリカの"], correctAns:"大学に"},
{level:"N4", section:"Susun Kalimat (★)", qText:"これからは　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: 物に／食べる／気をつけようと／きめた — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["物に","食べる","気をつけようと","きめた"], correctAns:"気をつけようと"},
{level:"N4", section:"Susun Kalimat (★)", qText:"＿＿　＿＿　★　＿＿　おくれた。<br><small style='color:var(--sub)'>Susun: 止まった／ことで／電車が／会社に — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["止まった","ことで","電車が","会社に"], correctAns:"ことで"},
{level:"N4", section:"Susun Kalimat (★)", qText:"この町には　＿＿　＿＿　★　＿＿　ます。<br><small style='color:var(--sub)'>Susun: あり／ところが／多くの／よい — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["あり","ところが","多くの","よい"], correctAns:"ところが"},
{level:"N4", section:"Susun Kalimat (★)", qText:"つぎの会議　＿＿　＿＿　★　＿＿　そうだ。<br><small style='color:var(--sub)'>Susun: に／は／10日後／開かれる — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["に","は","10日後","開かれる"], correctAns:"に"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【１】に入るものは？", options:["ことに","ことが","ことも","ことの"], correctAns:"ことに"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【２】に入るものは？", options:["さんぽ中と","さんぽ中も","さんぽ中が","さんぽ中の"], correctAns:"さんぽ中の"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【３】に入るものは？", options:["される","された","されば","されず"], correctAns:"される"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【４】に入るものは？", options:["ほど","から","こそ","けど"], correctAns:"から"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【５】に入るものは？", options:["走った","走ったり","走ろう","走るよう"], correctAns:"走ろう"},

/* ============ N3 — Tata Bahasa (JCT3 D 文法) ============ */
{level:"N3", section:"Tata Bahasa", qText:"今日の授業では、環境問題に（　）話し合いましょう。", options:["とって","かけて","ついて","おいて"], correctAns:"ついて"},
{level:"N3", section:"Tata Bahasa", qText:"今回は合格できなかったが、次（　）は絶対に合格したい。", options:["など","こそ","ほど","まで"], correctAns:"こそ"},
{level:"N3", section:"Tata Bahasa", qText:"５年（　）に友人に会ったが、全く変わっていなかった。", options:["きり","だけ","ぶり","さえ"], correctAns:"ぶり"},
{level:"N3", section:"Tata Bahasa", qText:"ここ数年で、平均気温は上がっていく（　）。", options:["一方だ","一回だ","一点だ","一体だ"], correctAns:"一方だ"},
{level:"N3", section:"Tata Bahasa", qText:"この試験に合格するには知識（　）、考える力も必要だ。", options:["だけでも","だけでなく","だけでは","だけなら"], correctAns:"だけでなく"},
{level:"N3", section:"Tata Bahasa", qText:"明日は遠足なので、（　）よいですね。", options:["晴れそう","晴れるかも","晴れるのに","晴れると"], correctAns:"晴れると"},
{level:"N3", section:"Tata Bahasa", qText:"彼女の笑顔は、（　）太陽のように明るい。", options:["まるで","決して","まさか","もしも"], correctAns:"まるで"},
{level:"N3", section:"Tata Bahasa", qText:"Ａ「昨日新しく学校に来た子の名前、なんだ（　）？」Ｂ「田中ゆりさんだよ」", options:["っか","かな","っけ","よね"], correctAns:"っけ"},
{level:"N3", section:"Tata Bahasa", qText:"去年と（　）、今年の夏は雨の日が多い。", options:["比べず","比べて","比べる","比べろ"], correctAns:"比べて"},
{level:"N3", section:"Tata Bahasa", qText:"テレビをつけ（　）、家を出てしまいました。", options:["っぽく","たまま","ながらに","たって"], correctAns:"たまま"},
{level:"N3", section:"Tata Bahasa", qText:"体調が良くなれば、明日は買い物に行く（　）だ。", options:["うち","もの","ところ","つもり"], correctAns:"つもり"},
{level:"N3", section:"Tata Bahasa", qText:"今日中にレポートを終わらせる予定だったが、（　）終わらなかった。", options:["最後","最中","結局","途中"], correctAns:"結局"},
{level:"N3", section:"Tata Bahasa", qText:"Ａ「英語を話せますか？」Ｂ「日常会話（　）なら、話すことができます」", options:["くらい","しか","より","ついで"], correctAns:"くらい"},
{level:"N3", section:"Susun Kalimat (★)", qText:"さっき　＿＿　＿＿　★　＿＿　、明日は学校が休みになるだろう。<br><small style='color:var(--sub)'>Susun: 本当だと／話が／聞いた／すれば — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["本当だと","話が","聞いた","すれば"], correctAns:"本当だと"},
{level:"N3", section:"Susun Kalimat (★)", qText:"私が　＿＿　＿＿　★　＿＿　ください。<br><small style='color:var(--sub)'>Susun: とおりに／折り紙を／説明した／折って — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["とおりに","折り紙を","説明した","折って"], correctAns:"折り紙を"},
{level:"N3", section:"Susun Kalimat (★)", qText:"皆が練習しているのに、　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: 休む／私だけ／いかない／わけには — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["休む","私だけ","いかない","わけには"], correctAns:"わけには"},
{level:"N3", section:"Susun Kalimat (★)", qText:"お菓子を買ってきたので、ここから　＿＿　＿＿　★　＿＿　ください。<br><small style='color:var(--sub)'>Susun: いって／一つずつ／持って／一人 — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["いって","一つずつ","持って","一人"], correctAns:"持って"},
{level:"N3", section:"Susun Kalimat (★)", qText:"実は知っていたが、　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: ふりを／知らない／した／何も — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["ふりを","知らない","した","何も"], correctAns:"ふりを"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>私は最近、運動不足だ。高校生のときまでは体育の授業やクラブ活動【１】があったため、少なくとも１週間に３回ほどは運動をしていた。しかし、大学に入ってからは【２】運動をしなくなってしまったのだ。そこで、私は先月、近所のテニススクールに入った。運動不足だと健康に良くないし、このままだと【３】と思ったからだ。ところが、そこまではげしい運動をしたわけではないのに、先週テニスをしている途中で腰が痛くなってしまった。【４】痛みではなかったので数日で良くなったが、運動不足が原因だと思うと少し悲しくなった。そのため、少しでも運動をしようと思い、今日からは家から駅までの間をバスに【５】に歩くことにした。<br><br>【１】に入るものは？", options:["とも","など","たち","ずつ"], correctAns:"など"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【２】に入るものは？", options:["ふと","いくら","全く","なるべく"], correctAns:"全く"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【３】に入るものは？", options:["太ってくれる","太ってあげる","太ってしまう","太っておこう"], correctAns:"太ってしまう"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【４】に入るものは？", options:["ひどい","かたい","おさない","かしこい"], correctAns:"ひどい"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【５】に入るものは？", options:["乗りぬ","乗らぬ","乗りず","乗らず"], correctAns:"乗らず"},

/* ============ N2 準上級 (JCT2 A) — Kosakata tambahan ============ */
{level:"N2", section:"Cara Baca Kanji", qText:"よい職場を<b>紹介</b>してもらう。", options:["じょうそう","じゅんけい","しゅんこう","しょうかい"], correctAns:"しょうかい"},
{level:"N2", section:"Cara Baca Kanji", qText:"切れ味の<b>鈍い</b>包丁では、トマトがうまく切れない。", options:["おも","おそ","にぶ","かた"], correctAns:"にぶ"},
{level:"N2", section:"Cara Baca Kanji", qText:"部屋の<b>隅</b>でしゃがみこむ。", options:["はし","おき","なか","すみ"], correctAns:"すみ"},
{level:"N2", section:"Cara Baca Kanji", qText:"彼女が欲しがっていたものを<b>贈る</b>。", options:["おく","つく","と","かざ"], correctAns:"おく"},
{level:"N2", section:"Cara Baca Kanji", qText:"彼には以前にも同じ話をしたので、説明を<b>省略</b>する。", options:["せいりょく","しょうりゃく","しゅんらく","しゅうろく"], correctAns:"しょうりゃく"},
{level:"N2", section:"Penulisan Kanji", qText:"首にスカーフを<b>まく</b>。", options:["券","巻","真","包"], correctAns:"巻"},
{level:"N2", section:"Penulisan Kanji", qText:"もったいなくて<b>すてられない</b>。", options:["接","捨","拾","技"], correctAns:"捨"},
{level:"N2", section:"Penulisan Kanji", qText:"地方の<b>のうそん</b>で暮らしている。", options:["濃厚","漁港","豊富","農村"], correctAns:"農村"},
{level:"N2", section:"Penulisan Kanji", qText:"初めて参加した大会で、<b>どう</b>メダルをとった。", options:["銅","鉄","鉱","鋭"], correctAns:"銅"},
{level:"N2", section:"Penulisan Kanji", qText:"ごみを集めたあと、<b>せいそう</b>センターに持っていきました。", options:["高層","正装","清掃","政党"], correctAns:"清掃"},
{level:"N2", section:"Isian Kosakata", qText:"新たに組織の（　）会長となった。", options:["要","副","後","超"], correctAns:"副"},
{level:"N2", section:"Isian Kosakata", qText:"わたしは、りんごを皮（　）食べます。", options:["ごと","ぶり","つき","おき"], correctAns:"ごと"},
{level:"N2", section:"Isian Kosakata", qText:"彼は優れた人間（　）を備えている。", options:["的","化","状","性"], correctAns:"性"},
{level:"N2", section:"Isian Kosakata", qText:"大雨によって、町に深刻な（　）害が出ている。", options:["加","受","被","有"], correctAns:"被"},
{level:"N2", section:"Isian Kosakata", qText:"（　）経験の仕事なので、慣れるまで時間がかかりそうです。", options:["不","非","未","否"], correctAns:"未"},
{level:"N2", section:"Isian Kosakata", qText:"警察によって、関係者以外の立ち入りが（　）されている。", options:["禁止","停止","中止","休止"], correctAns:"禁止"},
{level:"N2", section:"Isian Kosakata", qText:"来月までに10万円を貯金することが（　）です。", options:["目印","目下","目標","目前"], correctAns:"目標"},
{level:"N2", section:"Isian Kosakata", qText:"正確に測らなくても、（　）の長さがそろっていれば大丈夫だよ。", options:["いちいち","だいたい","ときどき","ますます"], correctAns:"だいたい"},
{level:"N2", section:"Isian Kosakata", qText:"忘れ物を取りに帰ったために、学校に（　）してしまった。", options:["延期","延長","遅延","遅刻"], correctAns:"遅刻"},
{level:"N2", section:"Isian Kosakata", qText:"事前に準備をしていたため、仕事が（　）に進んだ。", options:["スムーズ","リズム","オリジナル","メモリー"], correctAns:"スムーズ"},
{level:"N2", section:"Makna Serupa", qText:"困っている人に<b>適切</b>なアドバイスを送る。", options:["適当な","適応な","適用な","適量な"], correctAns:"適当な"},
{level:"N2", section:"Makna Serupa", qText:"ていねいな<b>説明</b>で、数学の問題の内容がよくわかった。", options:["解説","伝説","説得","説教"], correctAns:"解説"},
{level:"N2", section:"Makna Serupa", qText:"<b>やむを得ない</b>事情で会議を欠席する。", options:["内容がわからない","重要ではない","納得できない","仕方ない"], correctAns:"仕方ない"},
{level:"N2", section:"Makna Serupa", qText:"もし書類の内容が間違っていたら、契約を<b>白紙に戻す</b>ことになる。", options:["修正する","新しいものに変える","なかったことにする","同じことをくり返す"], correctAns:"なかったことにする"},
{level:"N2", section:"Makna Serupa", qText:"あの人は<b>クリーンな</b>政治家だと評判だ。", options:["容姿が優れている","悪いことをしない","気が弱く消極的な","長く経験を積んだ"], correctAns:"悪いことをしない"},
{level:"N2", section:"Penggunaan Kata", qText:"上達", options:["彼女はテニスの上達だから、筆記試験を受けずに大学に合格した。","初めての体験でこれだけ上手にできたなら上達だろう。","部長に上達する必要があるので、10時までに資料を用意してください。","毎日くり返し練習したおかげで、ずいぶんと上達した。"], correctAns:"毎日くり返し練習したおかげで、ずいぶんと上達した。"},
{level:"N2", section:"Penggunaan Kata", qText:"合同", options:["正しいと思う意見に合同する。","この映画は、別の映画作品とまったく合同な内容になっている。","これは二人の芸術家が合同で作り上げた作品です。","明後日は駅前で合同しよう。"], correctAns:"これは二人の芸術家が合同で作り上げた作品です。"},
{level:"N2", section:"Penggunaan Kata", qText:"産地", options:["向こうに見える青い屋根の建物が、私の産地です。","今も世界中で、牛が産地されている。","この美味しいメロンの産地はどこですか？","生まれたばかりの赤ちゃんを見て、産地な気分になった。"], correctAns:"この美味しいメロンの産地はどこですか？"},
{level:"N2", section:"Penggunaan Kata", qText:"そっくり", options:["妹の笑った顔が、父親にそっくりだ。","急な仕事が入ってしまい、そっくりする。","うしろの人にもそっくりがよく見えるように向きを変える。","彼はそっくりした性格の人だ。"], correctAns:"妹の笑った顔が、父親にそっくりだ。"},
{level:"N2", section:"Penggunaan Kata", qText:"シンポジウム", options:["文章中にシンポジウムな表現が多く用いられている。","最新の研究に関するシンポジウムが開かれた。","疲れたときには、シンポジウムすることで体を休めるとよい。","先生の教えが、私にとってのシンポジウムとなっている。"], correctAns:"最新の研究に関するシンポジウムが開かれた。"},

/* ============ N2 準上級 — Tata Bahasa (JCT2 A 文法) ============ */
{level:"N2", section:"Tata Bahasa", qText:"もう少しで原稿が完成するので、ぎりぎり（　）待ってもらえませんか。", options:["ほど","のように","まで","から"], correctAns:"まで"},
{level:"N2", section:"Tata Bahasa", qText:"彼は真面目に練習（　）、偉大な選手になっていただろう。", options:["していたら","したので","するから","しようと"], correctAns:"していたら"},
{level:"N2", section:"Tata Bahasa", qText:"次の休みは本を読んだり、絵を（　）過ごそう。", options:["描いて","描くように","描いたりして","描くときに"], correctAns:"描いたりして"},
{level:"N2", section:"Tata Bahasa", qText:"弟のおやつをだれが勝手に食べたのか知って（　）、知らないふりをした。", options:["おこうと","いながら","いようと","いるまいと"], correctAns:"いながら"},
{level:"N2", section:"Tata Bahasa", qText:"何度も確認したのに間違えることなんて、（　）がない。", options:["ありえ","あること","あろうこと","あるはず"], correctAns:"あるはず"},
{level:"N2", section:"Tata Bahasa", qText:"授業の内容については吉田先生に（　）していただきます。", options:["お申し付け","ご話","お申し込み","ご説明"], correctAns:"ご説明"},
{level:"N2", section:"Tata Bahasa", qText:"今日の15時に、先生が私の家に（　）ます。", options:["伺い","いらっしゃい","参り","行かれ"], correctAns:"いらっしゃい"},
{level:"N2", section:"Tata Bahasa", qText:"日も落ちてきたし、もうそろそろ遊びは終わりに（　）。", options:["しよう","ならなければ","した","なっている"], correctAns:"しよう"},
{level:"N2", section:"Tata Bahasa", qText:"合格の連絡がないということは、（　）、不合格ということだ。", options:["それでも","ゆえに","そして","つまり"], correctAns:"つまり"},
{level:"N2", section:"Tata Bahasa", qText:"全国大会に出場（　）、毎日の練習メニューを考える。", options:["するけれども","するために","しようとも","せねば"], correctAns:"するために"},
{level:"N2", section:"Tata Bahasa", qText:"外に出た（　）雨が降り始めた。", options:["とすれば","ところが","とたんに","といえば"], correctAns:"とたんに"},
{level:"N2", section:"Susun Kalimat (★)", qText:"どこでも　＿＿　＿＿　★　＿＿　良いところのひとつだ。<br><small style='color:var(--sub)'>Susun: 飲めるのは／水が／日本の／水道から出る — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["飲めるのは","水が","日本の","水道から出る"], correctAns:"水が"},
{level:"N2", section:"Susun Kalimat (★)", qText:"いつもご飯を　＿＿　＿＿　★　＿＿　食材を食べたい。<br><small style='color:var(--sub)'>Susun: ぜいたくな／たまには／済ますので／安く — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["ぜいたくな","たまには","済ますので","安く"], correctAns:"たまには"},
{level:"N2", section:"Susun Kalimat (★)", qText:"一年の中で　＿＿　＿＿　★　＿＿　よく目を通しておこう。<br><small style='color:var(--sub)'>Susun: 重要な／資料に／会議なので／最も — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["重要な","資料に","会議なので","最も"], correctAns:"会議なので"},
{level:"N2", section:"Susun Kalimat (★)", qText:"＿＿　＿＿　★　＿＿　ことが私の夢です。<br><small style='color:var(--sub)'>Susun: 世界中を／回る／旅に／出て — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["世界中を","回る","旅に","出て"], correctAns:"旅に"},
{level:"N2", section:"Susun Kalimat (★)", qText:"外の　＿＿　＿＿　★　＿＿　着る服を選ぶのがむずかしい。<br><small style='color:var(--sub)'>Susun: 暖かくて／室内は／気温は／低いが — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["暖かくて","室内は","気温は","低いが"], correctAns:"室内は"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>スポーツは、なぜあそこまで人々を感動【１】のだろうか。選手の技術の高さは【２】のこと、チームメートとのコンビネーションプレー、そこから読み取れる選手同士の信頼や友情、選手全員がひとつの目標に全力で向かっていくという熱が、私たちの心を動かす。さらに、実際にプレーをする選手だけではなく、選手を現場でサポートする人々もまた、同じ目標に向かっていく仲間として注目を集めることも少なくない。試合に出てプレーをすることはないにも関わらず、サポートをする人々がテレビで【３】ことも今日では当たり前になっている。【４】、私たちは選手の磨き抜かれた技術よりも、多くの人々が同じ目標を持ち、力を合わせて行動するところにさらなる感動を覚えているのではないのだろうか。私はスポーツを通じて、人間が何よりも【５】な生き物であることを教えられた気分になるのである。<br><br>【１】に入るものは？", options:["ある","する","できる","させる"], correctAns:"させる"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【２】に入るものは？", options:["もちろん","なるほど","なにより","さいわい"], correctAns:"もちろん"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【３】に入るものは？", options:["観る","出演される","放送する","取り上げられる"], correctAns:"取り上げられる"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【４】に入るものは？", options:["なぜなら","おそらく","しかし","または"], correctAns:"しかし"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【５】に入るものは？", options:["一般的","一時的","社会的","積極的"], correctAns:"社会的"},
/* ============ N1 (dari tes JLPT N1 - Bunpou & Kosakata) — 106 soal ============ */
{"level":"N1","section":"Tata Bahasa","qText":"箱の中身、（　）にしよう。","options":["見ないこと","見なかったこと","見ないもの","見なかったもの"],"correctAns":"見なかったこと"},
{"level":"N1","section":"Tata Bahasa","qText":"京都（　）体験をしてみたいです。","options":["なり","なくして","ながらに","ならではの"],"correctAns":"ならではの"},
{"level":"N1","section":"Tata Bahasa","qText":"それは（　）説得力のある考えだったが、なぜか私は納得しなかった。","options":["あえて","まさか","なかなか","かえって"],"correctAns":"なかなか"},
{"level":"N1","section":"Tata Bahasa","qText":"その看板が小さすぎて、よく見なかったら（　）。","options":["見逃すところだった","見逃そうとした","見逃したわけだ","見逃さなくてはならなかった"],"correctAns":"見逃すところだった"},
{"level":"N1","section":"Tata Bahasa","qText":"EURO 2020 中止という聞きたくない話が現実に（　）。","options":["なったようだ","なりかけている","なりかねない","なってはならない"],"correctAns":"なりかねない"},
{"level":"N1","section":"Tata Bahasa","qText":"英語が話せなくて道を（　）聞けない。","options":["聞いては","聞くには","聞こうにも","聞かずとも"],"correctAns":"聞こうにも"},
{"level":"N1","section":"Tata Bahasa","qText":"人生には、とにかく（　）わからないってことが多すぎる。","options":["やってるって","やってみなきゃ","やっちゃうのが","やっちゃおうと"],"correctAns":"やってみなきゃ"},
{"level":"N1","section":"Tata Bahasa","qText":"メキシコは北米自由貿易協定（ＮＡＦＴＡ）が（　）、世界最大にして最も活力のある市場に、効率よく輸出を行うことができる。","options":["あってはなかっては","あろうとなかろうと","あるといいないといい","あるがまいが"],"correctAns":"あろうとなかろうと"},
{"level":"N1","section":"Tata Bahasa","qText":"先日も注文をいただきました。皆さん一口食べるだけで口を揃えて「もうほかのケーキは食べられない！」と言って下さるんです。本当に（　）限りです。","options":["嬉しそう","嬉しくて","嬉しかった","嬉しい"],"correctAns":"嬉しい"},
{"level":"N1","section":"Tata Bahasa","qText":"トランプ大統領は個人情報が中国政府に（　）として、安全保障上の懸念を理由にティックトックの禁止措置を打ち出した。","options":["流出してしまってはならない","流出してしまいつつある","流出してしまうところだ","流出するおそれがある"],"correctAns":"流出するおそれがある"},
{"level":"N1","section":"Tata Bahasa","qText":"私の調べたかぎりでは、何人と（　）その男を害することを欲するような理由が、どこにもまったく見あたらないんですよ。","options":["いえども","いったらば","いえばこそ","いったからには"],"correctAns":"いえども"},
{"level":"N1","section":"Tata Bahasa","qText":"さすがに一流の歌手（　）違う。１回の出演料が数百万円だという。","options":["ともすると","ともなると","のはいえ","といっても"],"correctAns":"ともなると"},
{"level":"N1","section":"Tata Bahasa","qText":"車が角を曲がると、橋本は身を起こし、わたしの血（　）の腕を握った。","options":["ずくめ","まみれ","ばはり","みずく"],"correctAns":"まみれ"},
{"level":"N1","section":"Tata Bahasa","qText":"人前で演技をするのは初めての経験（　）、彼はひどく緊張していた。","options":["とあって","にあって","として","にして"],"correctAns":"とあって"},
{"level":"N1","section":"Tata Bahasa","qText":"コンピュータがデジタルハブになると最初に見（　）のはわが社だ。","options":["ぬいて","ぬく","ぬいた","ぬき"],"correctAns":"ぬいた"},
{"level":"N1","section":"Tata Bahasa","qText":"もう少し早く病院に行けば助かった（　）、放っておいたので、手遅れになってしまった。","options":["もので","ものか","ものを","ものに"],"correctAns":"ものを"},
{"level":"N1","section":"Tata Bahasa","qText":"中村は三杯目のウォッカを飲みほし、キッチンの窓から外を見る（　）見た。","options":["ばかりか","のみならず","ともなしに","どころではなく"],"correctAns":"ともなしに"},
{"level":"N1","section":"Tata Bahasa","qText":"彼は自分の息子がどうなっているかを、一度（　）調べようとはしない。","options":["よりも","だけは","たりとも","ばかりか"],"correctAns":"たりとも"},
{"level":"N1","section":"Tata Bahasa","qText":"子どものころ、死については（　）だに恐ろしかった。","options":["考え","考えた","考えて","考える"],"correctAns":"考える"},
{"level":"N1","section":"Tata Bahasa","qText":"僕が席に着く（　）、彼女が待ってましたとばかりにやって来た。","options":["次第で","や否や","が最後","末に"],"correctAns":"や否や"},
{"level":"N1","section":"Tata Bahasa","qText":"彼は思わせ（　）な笑みを浮かべてわたしを見た。","options":["びる","だの","すら","ぶり"],"correctAns":"ぶり"},
{"level":"N1","section":"Tata Bahasa","qText":"苦難に満ちたあの人の人生は、涙なくしては（　）。","options":["語る","語らない","語れる","語れない"],"correctAns":"語れない"},
{"level":"N1","section":"Tata Bahasa","qText":"他人を犠牲にする（　）なしに、個人の望みを達成することは困難だと考えている人もいます。","options":["の","こと","もの","ところ"],"correctAns":"こと"},
{"level":"N1","section":"Tata Bahasa","qText":"そこは小さなアパートメントで、においについて言えば、バニラの香りのキャンドルと古いカーペットが負けじと張り合っているらしかった。家具や装飾品は貧相としか（　）。","options":["言いそうもない","言うそうもない","言うようがない","言いようがない"],"correctAns":"言いようがない"},
{"level":"N1","section":"Tata Bahasa","qText":"わかりました。貸金庫に何がはいっているの（　）、それを三浦さんに届けましょう。","options":["であれ","ごとき","まじき","にして"],"correctAns":"であれ"},
{"level":"N1","section":"Tata Bahasa","qText":"あいつはどこへ逃げたかは（　）、どこから来たかだけはわかりそうです。","options":["わからるほどで","わからるまでも","わからないほどで","わからないまでも"],"correctAns":"わからないまでも"},
{"level":"N1","section":"Tata Bahasa","qText":"映画を見終わって、主人公の生き方に（　）、自分の生き方がいかにいいかげんだったか、強く反省した。","options":["かけて","よって","あって","ひきかえ"],"correctAns":"ひきかえ"},
{"level":"N1","section":"Tata Bahasa","qText":"髪（　）、夕べはふさふさと豊かだったのに、けさはまだシャワーを浴びていないのか、べっとりと湿っている。","options":["とみると","ときている","ときたら","といわず"],"correctAns":"ときたら"},
{"level":"N1","section":"Tata Bahasa","qText":"チンパンジーは人間の模倣を（　）のみならず、互いに協力して共同作業をしているらしいという報告もある。","options":["して","する","せず","しまい"],"correctAns":"する"},
{"level":"N1","section":"Tata Bahasa","qText":"びっくりした。ただただ、ぼうぜん。あの瞬間のことは、（　）忘れることができない。","options":["忘れようにも","忘れても","忘れようとしても","忘れようとも"],"correctAns":"忘れようにも"},
{"level":"N1","section":"Tata Bahasa","qText":"たった三十分のあいだに、高木の変わり様（　）。","options":["といえなかった","といおうもなかった","といってもなかった","といったらなかった"],"correctAns":"といったらなかった"},
{"level":"N1","section":"Tata Bahasa","qText":"強風で、家から（　）出られなかった。","options":["出ようにも","出ようが","出たなら","出れば"],"correctAns":"出ようにも"},
{"level":"N1","section":"Tata Bahasa","qText":"急に大学を退学したのはなぜか、わたし（　）思う理由があります。","options":["だに","なりに","ままに","なしに"],"correctAns":"なりに"},
{"level":"N1","section":"Tata Bahasa","qText":"損失を最小限度に（　）ことには気持ちがやすまらない。","options":["くいとめた","くいとめる","くいとめない","くいとめなかった"],"correctAns":"くいとめない"},
{"level":"N1","section":"Tata Bahasa","qText":"脱ぎ捨てられたドレスたちが床（　）、ベッド（　）、椅子（　）広げられ、鮮やかな色があれこれと重なり、そこにはぐれたリボンがごっちゃになっている。","options":["としたって/としたって/としたって","とあれば/とあれば/とあれば","ともなく/ともなく/ともなく","といわず/といわず/といわず"],"correctAns":"といわず/といわず/といわず"},
{"level":"N1","section":"Tata Bahasa","qText":"わたしたちは小道に入るころには、細かい雨さえ降りだしてきた。だが千葉くんは（　）、もどかしげに路をいそぐし、わたしたちもあとに続いた。","options":["ものともせず","ものとして","ものならず","ものながら"],"correctAns":"ものともせず"},
{"level":"N1","section":"Tata Bahasa","qText":"白鳥がそばを離れてからはまた独りでおり、議論が白熱していくの（　）、一言も発さずにいた。","options":["をもとに","をよそに","をもって","をこめて"],"correctAns":"をよそに"},
{"level":"N1","section":"Tata Bahasa","qText":"できるかぎり早く新しいウェディングドレスを作ると約束しないかぎり結婚式はおこなわない」と彼女が涙（　）訴えた。","options":["ながら","ながらに","ながらも","ながらで"],"correctAns":"ながらに"},
{"level":"N1","section":"Tata Bahasa","qText":"申請書の提出締め切りは明日の午後４時だが、早めに出せればそれに（　）。","options":["こしたことはない","こすことはない","こしたことではない","こすことではない"],"correctAns":"こしたことはない"},
{"level":"N1","section":"Tata Bahasa","qText":"彼はテレビゲームが大好きでゲーム機の前に（　）最後、何時間でもやり続ける。","options":["すわったが","すわったの","すわるの","すわったから"],"correctAns":"すわったが"},
{"level":"N1","section":"Tata Bahasa","qText":"まだ十五の小娘（　）、彼女にはプランテーションの女主人として責任を引き受ける心構えが充分にできている。","options":["といえば","とばかりに","とはいえ","ともなく"],"correctAns":"とはいえ"},
{"level":"N1","section":"Tata Bahasa","qText":"身長２メートル（　）大男が、突然、目の前に現れた。","options":["だけある","からする","だけする","からある"],"correctAns":"からある"},
{"level":"N1","section":"Tata Bahasa","qText":"今日び、鉄製のレールの交換（　）、あらゆる鉄製品は補充がきわめて困難な状況にある。","options":["はおかず","はさておき","はおろか","はそっちのけで"],"correctAns":"はおろか"},
{"level":"N1","section":"Tata Bahasa","qText":"話をおもしろくするためだろうか、あの人はものごとを大げさに言う（　）。","options":["きらいがある","きらいではない","きらいらしい","きらいがない"],"correctAns":"きらいがある"},
{"level":"N1","section":"Tata Bahasa","qText":"その頃すでに、いたずらではすまされぬことをしでかして、私が裁判所から注意を受ける（　）。","options":["しまつだ","しまいだ","かぎりだ","おわりだ"],"correctAns":"しまつだ"},
{"level":"N1","section":"Tata Bahasa","qText":"大阪でわたしに会って（　）、あなたの人生はいたってスキャンダラスなものになっているし、その責任の大半はわたしにある。","options":["というもの","はいうものの","たるもの","からというもの"],"correctAns":"からというもの"},
{"level":"N1","section":"Tata Bahasa","qText":"前線の兵力がますます衰え、ますます後方へと退却を（　）。","options":["余儀なくしている","余儀なくされている","余儀なくさせている","余儀なくしてもらっている"],"correctAns":"余儀なくされている"},
{"level":"N1","section":"Tata Bahasa","qText":"人を殺さ（　）毒物を三日前に飲まされたのに、あなたがどうしてまだ生きているの？","options":["ずとも","ずじまい","ずにはおかない","ずにはならない"],"correctAns":"ずにはおかない"},
{"level":"N1","section":"Tata Bahasa","qText":"腕のいい熟練工たちであり、彼ら（　）連合軍はプストル、ライフル、大砲、弾薬などを造るのにもひどく難儀していただろう。","options":["なければ","なしには","ないので","ないのに"],"correctAns":"なしには"},
{"level":"N1","section":"Tata Bahasa","qText":"あの作家は天才なのだから、わずか三日で傑作を書いたからといって、驚く（　）。","options":["にはあたらない","べきことだ","にきまっている","にちがいない"],"correctAns":"にはあたらない"},
{"level":"N1","section":"Isian Kosakata","qText":"ケネディ殺害の容疑者は（　）に謎を残したままマフィアに撃たれて死亡した。","options":["動機","本音","動力","下心"],"correctAns":"動機"},
{"level":"N1","section":"Isian Kosakata","qText":"いつ見つけても（　）の早いがんでは予後が悪く、遅いがんは予後がいい。早くても遅くても意味はないのです。","options":["先進","増進","進出","進行"],"correctAns":"進行"},
{"level":"N1","section":"Isian Kosakata","qText":"インターネット広告（　）と広告の効果の関係について考えてみよう。","options":["値","費","料","額"],"correctAns":"費"},
{"level":"N1","section":"Isian Kosakata","qText":"この数年間で千葉や隣接県では女児連れ去り事件が多発していた。まだ（　）解決の案件もあるが、未遂に終わり、容疑者が逮捕されたケースもある。","options":["非","双","未","無"],"correctAns":"未"},
{"level":"N1","section":"Isian Kosakata","qText":"辞書を引いたら、最初に（　）されている語義だけでなく、すべての語義をざっと確認する習慣を付けましょう。","options":["記載","援用","参照","出典"],"correctAns":"記載"},
{"level":"N1","section":"Isian Kosakata","qText":"専門学校で、デザインという仕事の難しさに（　）することになりました。","options":["対決","直面","抵抗","挑戦"],"correctAns":"直面"},
{"level":"N1","section":"Isian Kosakata","qText":"この機械を（　）にはかなりの技術が必要だ。","options":["使いこなす","使いおわる","使いはたす","使いすてる"],"correctAns":"使いこなす"},
{"level":"N1","section":"Isian Kosakata","qText":"最近の青少年はしっかりしているようだが、精神的に（　）面がある。","options":["しぶい","だるい","ゆるい","もろい"],"correctAns":"もろい"},
{"level":"N1","section":"Isian Kosakata","qText":"何回会議をやっても結論が出ないので、（　）いやになった。","options":["つくづく","わざわざ","ぞくぞくと","くれぐれも"],"correctAns":"つくづく"},
{"level":"N1","section":"Isian Kosakata","qText":"不況の影響で、この地域の中小企業は（　）倒産した。","options":["いまさら","ひたすら","のきなみ","ひいては"],"correctAns":"のきなみ"},
{"level":"N1","section":"Isian Kosakata","qText":"年をとると、だんだん新しい考え方が（　）にくくなる。","options":["うけあい","うけいれ","うけとり","うけもち"],"correctAns":"うけいれ"},
{"level":"N1","section":"Isian Kosakata","qText":"このアンケートに協力するかしないかは自由で、（　）はしないということにしたい。","options":["圧迫","強制","催促","一致"],"correctAns":"強制"},
{"level":"N1","section":"Isian Kosakata","qText":"アップルは１０億ドルの赤字に（　）し、１９９１年に７０ドルだった株価は１４ドルと低迷した。","options":["転落","減少","緊縮","締付"],"correctAns":"転落"},
{"level":"N1","section":"Isian Kosakata","qText":"（　）のほうの女の子がファッションショーで見るみたいな優雅な足取りですばやく去った。","options":["小売","小銭","小柄","小児"],"correctAns":"小柄"},
{"level":"N1","section":"Isian Kosakata","qText":"ワシントン条約は、サイの角の国際取引を（　）いるが、ベトナムや中国への密輸はなくならない。","options":["案じて","禁じて","報じて","興じて"],"correctAns":"禁じて"},
{"level":"N1","section":"Isian Kosakata","qText":"もちろん、こうしたロシアの動きを受けて、北極圏の他の国々も軍事面で北方を注視するようになり、（　）も北に移している。","options":["軍隊力","軍艦力","軍事力","軍備力"],"correctAns":"軍事力"},
{"level":"N1","section":"Isian Kosakata","qText":"そのとき、かなたからサイレンの音が聞こえ、疲労（　）が自分に重くのしかかるのを感じた。","options":["力","感","覚","性"],"correctAns":"感"},
{"level":"N1","section":"Isian Kosakata","qText":"密猟からサイを守るための（　）は、ほぼマイケルのような飼育家の肩にのしかかっているのが現状だ。","options":["負担","厄介","積載","干渉"],"correctAns":"負担"},
{"level":"N1","section":"Isian Kosakata","qText":"体力が回復するまで二、三週間（　）にして、抗生物質と流動食を与える必要がある。","options":["沈静","平和","安静","円満"],"correctAns":"安静"},
{"level":"N1","section":"Isian Kosakata","qText":"この仕事には特別な資格はいらないが、日本語がある程度できることが（　）。","options":["のぞましい","ふさわしい","まちどおしい","めざましい"],"correctAns":"のぞましい"},
{"level":"N1","section":"Isian Kosakata","qText":"彼は（　）性格でみんなに好かれている。","options":["明確な","明解な","明朗な","明白な"],"correctAns":"明朗な"},
{"level":"N1","section":"Isian Kosakata","qText":"首相の軽率な発言で、良好であった両国の関係が（　）。","options":["きずきはじめた","きたえはじめた","きしみはじめた","きざみはじめた"],"correctAns":"きしみはじめた"},
{"level":"N1","section":"Isian Kosakata","qText":"わたしの秘書はとても（　）がいいので助かっている。","options":["てぎわ","しらべ","こころえ","うちわけ"],"correctAns":"てぎわ"},
{"level":"N1","section":"Isian Kosakata","qText":"この都市は、周辺から人が集まりすぎて（　）状態だ。","options":["過密","窮屈","不潔","不服"],"correctAns":"過密"},
{"level":"N1","section":"Isian Kosakata","qText":"無辜の者が（　）されるという不正義ほど理不尽なものはこの世に存在しない。","options":["裁決","所見","審判","処罰"],"correctAns":"処罰"},
{"level":"N1","section":"Isian Kosakata","qText":"Ｘ線撮影をして、（　）出血の徴候がないことを確認した。","options":["内","上","中","下"],"correctAns":"内"},
{"level":"N1","section":"Isian Kosakata","qText":"この国内取引禁止措置は、近く（　）されるかもしれない。","options":["解約","解放","解釈","解除"],"correctAns":"解除"},
{"level":"N1","section":"Isian Kosakata","qText":"店舗の大きさはブランドの価値を示すと社長は（　）した。","options":["識別","指摘","認定","束縛"],"correctAns":"指摘"},
{"level":"N1","section":"Isian Kosakata","qText":"波打ち（　）では、鳥たちが目を凝らしてエサをついばんでいる。","options":["際","辺","側","端"],"correctAns":"際"},
{"level":"N1","section":"Isian Kosakata","qText":"Suica の（　）は、実は国鉄時代から進められてきた。","options":["搾取","収奪","拓殖","開発"],"correctAns":"開発"},
{"level":"N1","section":"Isian Kosakata","qText":"国内取引を解禁することには（　）な反対論もある。","options":["堅調","強硬","健全","固体"],"correctAns":"強硬"},
{"level":"N1","section":"Isian Kosakata","qText":"これから、この経験を仕事に（　）いきたいと思う。","options":["生かして","慣れて","使って","努力して"],"correctAns":"生かして"},
{"level":"N1","section":"Isian Kosakata","qText":"最近仕事が忙しくて、社員は（　）気味だ。","options":["過多","過剰","過労","過密"],"correctAns":"過労"},
{"level":"N1","section":"Isian Kosakata","qText":"周囲の人々の気持ちに（　）して対策を考えるべきだ。","options":["気配","配慮","配置","分配"],"correctAns":"配慮"},
{"level":"N1","section":"Isian Kosakata","qText":"知らない漢字でも、その部首を見て意味を（　）できることがある。","options":["予知","予言","推進","類推"],"correctAns":"類推"},
{"level":"N1","section":"Isian Kosakata","qText":"たいこの音が聞こえてきて、祭りの（　）がいちだんと盛り上がってきた。","options":["ブーム","ポーズ","ムード","リード"],"correctAns":"ムード"},
{"level":"N1","section":"Isian Kosakata","qText":"自然保護を（　）に入れた開発計画が大事だ。","options":["思考","想像","促進","考慮"],"correctAns":"考慮"},
{"level":"N1","section":"Isian Kosakata","qText":"科学技術の歴史からみると、コンピューターの発明は（　）できごとだった。","options":["画期的な","周期的な","定期的な","末期的な"],"correctAns":"画期的な"},
{"level":"N1","section":"Isian Kosakata","qText":"高い木に登っている子供が落ちはしないかと、大人は（　）して見ている。","options":["はらはら","ひらひら","ぶかぶか","ふらふち"],"correctAns":"はらはら"},
{"level":"N1","section":"Isian Kosakata","qText":"大型の台風が近づいているので、きょうは出発を（　）ことにした。","options":["見はからう","見ならう","見のがす","見あわせる"],"correctAns":"見あわせる"},
{"level":"N1","section":"Isian Kosakata","qText":"あれ、まだ家にいたんですか。（　）もう出かけたのだと思っていました。","options":["きっかり","てっきり","じっくり","きっちり"],"correctAns":"てっきり"},
{"level":"N1","section":"Isian Kosakata","qText":"けがをしたが、その場ですぐ（　）処置をしたので、大事にはいたらなかった。","options":["救援","救助","応急","応援"],"correctAns":"応急"},
{"level":"N1","section":"Isian Kosakata","qText":"年をとったせいか、何をするのも（　）。","options":["まぎらわしい","なやましい","みすぼらしい","わずらわしい"],"correctAns":"わずらわしい"},
{"level":"N1","section":"Isian Kosakata","qText":"この古い寺の庭は（　）がある。","options":["おおすじ","おもむき","おとも","おそれ"],"correctAns":"おもむき"},
{"level":"N1","section":"Isian Kosakata","qText":"計画がうまく行くように、みんなで作戦を（　）。","options":["こめた","ねった","ほどこした","あつらえた"],"correctAns":"ねった"},
{"level":"N1","section":"Isian Kosakata","qText":"テレビ番組の表現が差別的だったので、さっそく放送局に（　）した。","options":["協議","決議","抗議","物議"],"correctAns":"抗議"},
{"level":"N1","section":"Isian Kosakata","qText":"仕事はできるだけ早めに始めるように（　）いる。","options":["いどんで","とりくんで","こころがけて","はかどって"],"correctAns":"こころがけて"},
{"level":"N1","section":"Isian Kosakata","qText":"田中さんは目上の人にはていねいだが、下の人にはとても（　）なる。","options":["おろかに","おろそかに","ぞんざいに","つきなみに"],"correctAns":"ぞんざいに"},
{"level":"N1","section":"Isian Kosakata","qText":"始めて会った瞬間、（　）的にこの人とはうまくいくと思った。","options":["主観","悲観","予感","直感"],"correctAns":"直感"},
{"level":"N1","section":"Isian Kosakata","qText":"彼は仕事に対する（　）があまい。","options":["常識","知識","認識","見識"],"correctAns":"認識"},
{"level":"N1","section":"Isian Kosakata","qText":"彼は将来（　）小説家だ。","options":["有効な","有利な","有益な","有望な"],"correctAns":"有望な"},
{"level":"N1","section":"Isian Kosakata","qText":"彼は（　）勢いで仕事を片付けていった。","options":["もうれつな","ものずきな","だいたんな","たくみな"],"correctAns":"もうれつな"},
{"level":"N1","section":"Isian Kosakata","qText":"この深刻な不況の中で、（　）見通しを持つ人は少ない。","options":["間接的な","平均的な","楽観的な","伝統的な"],"correctAns":"楽観的な"},
{"level":"N1","section":"Isian Kosakata","qText":"人間関係でこんなに苦労するなら、（　）この会社をやめてしまおう。","options":["いっこうに","いっしんに","いったい","いっそ"],"correctAns":"いっそ"},
{"level":"N1","section":"Isian Kosakata","qText":"建物に入るのに、いちいち証明書を見せなければならないので、本当に（　）。","options":["わずらわしい","まちどおしい","みすぼらしい","はなはだしい"],"correctAns":"わずらわしい"},
{"level":"N1","section":"Isian Kosakata","qText":"この選手は（　）が足りないので、いつも最後に負けてしまう。","options":["はげみ","はずみ","ねばり","むすび"],"correctAns":"ねばり"}
];
